version: "3.1"

services:
  devcontainer:
    image: ghcr.io/moveaxlab/oracle-db-job-queue-devcontainer:latest
    volumes:
      - .:/workspaces/cotral-go:cached
    command: sleep infinity

  database:
    image: container-registry.oracle.com/database/free:latest
    ports:
      - 1521:1521
      - 5500:5500
    environment:
      ORACLE_PWD: password
