name: test

on:
    push:
        branches: [ "main" ]

jobs:
    test:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/moveaxlab/oracle-db-job-queue-devcontainer:latest
        services:
            postgres:
                image: kartoza/postgis:15
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASS: postgres
                    POSTGRES_DBNAME: test
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 5432:5432

            oracle:
                image: container-registry.oracle.com/database/free:latest
                ports:
                    - 1521:1521
                    - 5500:5500
                env:
                    ORACLE_PWD: password

        steps:
        - uses: actions/checkout@v4
        - run: go test -v ./...
